<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <PublishAot>true</PublishAot>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <WarningsAsErrors>true</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\WebApi.Platform\WebApi.Platform.csproj"/>
        <ProjectReference Include="..\Generators\Generators\Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" Properties="PublishAot=false" />
    </ItemGroup>

    <ItemGroup>
        <!-- Needed to source-generated types for configuration -->
        <AdditionalFiles Include="appsettings.json"/>
        <AdditionalFiles Include="OpenApi/todos.openapi.yaml" />
    </ItemGroup>

</Project>
