using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Generators;

[Generator]
public class ServiceRegistrationGenerator : IIncrementalGenerator
{
    private const string AttrFqn = "Platform.Annotations.ServiceAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classSyntax = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttrFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax
                {
                    AttributeLists.Count: > 0,
                    TypeParameterList: null
                },
                transform: static (syntaxContext, _) =>
                {
                    var classDeclaration = (ClassDeclarationSyntax)syntaxContext.TargetNode;
                    var symbol = syntaxContext.SemanticModel.GetDeclaredSymbol(classDeclaration);
                    return symbol;
                })
            .Where(static s => s != null);

        var services = classSyntax.Select(static (sym, _) =>
        {
            var attr = sym!.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == AttrFqn);
            return (sym, attr);
        }).Where(static t => t.attr != null);

        var serviceModels = services.Select(static (t, _) =>
        {
            var (impl, attr) = t;
            // Mirrors Microsoft.Extensions.DependencyInjection.ServiceLifetime (no DI reference in analyzer assembly).
            var lifetime = 2; // Transient
            if (attr!.ConstructorArguments.Length >= 1 && attr.ConstructorArguments[0].Value is int lt)
            {
                lifetime = lt;
            }

            var asSelf = false;
            if (attr.ConstructorArguments.Length >= 2 && attr.ConstructorArguments[1].Value is bool b2)
            {
                asSelf = b2;
            }

            INamedTypeSymbol? asType = null;
            foreach (var na in attr.NamedArguments)
            {
                if (na is { Key: "As", Value.Value: INamedTypeSymbol ts })
                {
                    asType = ts;
                }
            }

            foreach (var na in attr.NamedArguments)
            {
                if (na is { Key: "AsSelf", Value.Value: bool b })
                {
                    asSelf = b;
                }
            }

            if (impl.IsAbstract || impl.DeclaredAccessibility != Accessibility.Public)
            {
                return null;
            }

            var implDisplay = impl.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var serviceTypes = ImmutableArray.CreateBuilder<string>();

            if (asType != null)
            {
                serviceTypes.Add(asType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }
            else
            {
                // Sensible default: if no explicit "As" is provided, register the implementation type.
                serviceTypes.Add(implDisplay);
            }

            if (asSelf && !serviceTypes.Contains(implDisplay))
            {
                serviceTypes.Add(implDisplay);
            }

            return new ServiceModel(
                implDisplay,
                lifetime,
                serviceTypes.ToImmutable()
            );
        });

        var collected = serviceModels.Where(static m => m != null).Collect();

        context.RegisterSourceOutput(collected, static (ctx, batch) =>
        {
            var models = batch
                .Where(static m => m != null)
                .Select(static m => m!)
                .OrderBy(static m => m.ImplementationType, StringComparer.Ordinal)
                .ToArray();

            ctx.AddSource("ServiceRegistration.g.cs", SourceText.From(Emit(models), Encoding.UTF8));
        });
    }

    private static string Emit(IReadOnlyList<ServiceModel> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("public static partial class GeneratedServiceRegistrationExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection RegisterGeneratedServices(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        if (models.Count > 0)
        {
            foreach (var model in models)
            {
                foreach (var serviceType in model.ServiceTypes.Distinct(StringComparer.Ordinal))
                {
                    EmitRegistration(sb, model.Lifetime, serviceType, model.ImplementationType);
                }
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitRegistration(StringBuilder sb, int lifetime, string serviceType, string implementationType)
    {
        var method = lifetime switch
        {
            0 => "AddSingleton",
            1 => "AddScoped",
            _ => "AddTransient"
        };

        if (string.Equals(serviceType, implementationType, StringComparison.Ordinal))
        {
            sb.AppendLine($"        services.{method}<{implementationType}>();");
        }
        else
        {
            sb.AppendLine($"        services.{method}<{serviceType}, {implementationType}>();");
        }
    }

    private sealed class ServiceModel(string implementationType, int lifetime, ImmutableArray<string> serviceTypes)
    {
        public string ImplementationType { get; } = implementationType;
        public int Lifetime { get; } = lifetime;
        public ImmutableArray<string> ServiceTypes { get; } = serviceTypes;
    }
}