using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Generators;

[Generator]
public class StrongIdGenerator : IIncrementalGenerator
{
    private const string AttrFqn = "Platform.Annotations.StrongIdAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.ForAttributeWithMetadataName<StrongIdModel>(
            AttrFqn,
            predicate: static (node, _) => node is StructDeclarationSyntax s && s.Modifiers.Any(SyntaxKind.PartialKeyword),
            transform: static (syntaxContext, _) =>
            {
                var symbol = syntaxContext.TargetSymbol;
                var attr = syntaxContext.Attributes[0];

                var underlyingArg = "global::System.Guid";
                if (attr.ConstructorArguments.Length == 1 && attr.ConstructorArguments[0].Value is ITypeSymbol typeSymbol)
                {
                    underlyingArg = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                }

                var displayString = string.Empty;
                if (symbol.ContainingNamespace is { IsGlobalNamespace: false })
                {
                    displayString = symbol.ContainingNamespace.ToDisplayString();
                }

                return new StrongIdModel
                {
                    Namespace = displayString,
                    Name = symbol.Name,
                    Accessibility = symbol.DeclaredAccessibility,
                    UnderlyingTypeDisplay = underlyingArg
                };
            }
        );

        var models = provider.Collect();

        context.RegisterSourceOutput(models, static (ctx, batch) =>
        {
            foreach (var model in batch)
            {
                ctx.AddSource($"{model.Name}.StrongId.g.cs", EmitSource(model));
            }
        });
    }

    private static SourceText EmitSource(StrongIdModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"{AccessibilityToCSharp(model.Accessibility)} readonly partial struct {model.Name} : global::System.IEquatable<{model.Name}>");
        sb.AppendLine("{");
        sb.AppendLine(EmitNew(model));
        sb.AppendLine(EmitTryParse(model));
        sb.AppendLine(EmitMustParse(model));
        sb.AppendLine();
        sb.AppendLine($"    public {model.Name}({model.UnderlyingTypeDisplay} value) => Value = value;");
        sb.AppendLine();
        sb.AppendLine($"    public {model.UnderlyingTypeDisplay} Value {{ get; }}");
        sb.AppendLine();
        sb.AppendLine("    public override string ToString() => Value.ToString() ?? string.Empty;");
        sb.AppendLine();
        sb.AppendLine($"    public static implicit operator {model.UnderlyingTypeDisplay}({model.Name} id) => id.Value;");
        sb.AppendLine($"    public static explicit operator {model.Name}({model.UnderlyingTypeDisplay} value) => new(value);");
        sb.AppendLine();
        sb.AppendLine($"    public bool Equals({model.Name} other) => global::System.Collections.Generic.EqualityComparer<{model.UnderlyingTypeDisplay}>.Default.Equals(Value, other.Value);");
        sb.AppendLine("    public override bool Equals(object? obj) => obj is " + model.Name + " other && Equals(other);");
        sb.AppendLine("    public override int GetHashCode() => global::System.Collections.Generic.EqualityComparer<" + model.UnderlyingTypeDisplay + ">.Default.GetHashCode(Value);");
        sb.AppendLine();
        sb.AppendLine($"    public static bool operator ==({model.Name} left, {model.Name} right) => left.Equals(right);");
        sb.AppendLine($"    public static bool operator !=({model.Name} left, {model.Name} right) => !left.Equals(right);");
        sb.AppendLine("}");
        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    private static string EmitNew(StrongIdModel model)
    {
        return model.UnderlyingTypeDisplay switch
        {
            "global::System.Guid" =>
                $"    public static {model.Name} New() => new(global::System.Guid.NewGuid());\n",
            "global::System.Int32" =>
                "    private static int _nextValue;\n" +
                $"    public static {model.Name} New() => new(global::System.Threading.Interlocked.Increment(ref _nextValue));\n",
            "global::System.Int64" =>
                "    private static long _nextValue;\n" +
                $"    public static {model.Name} New() => new(global::System.Threading.Interlocked.Increment(ref _nextValue));\n",
            _ =>
                $"    public static {model.Name} New() =>\n" +
                "        throw new global::System.NotSupportedException(\"New() is only supported for Guid, int, and long strong IDs.\");\n"
        };
    }

    private static string EmitTryParse(StrongIdModel model)
    {
        var name = model.Name;
        var underlying = model.UnderlyingTypeDisplay;

        var parseBody = model.UnderlyingTypeDisplay switch
        {
            "global::System.Guid" =>
                "        if (!global::System.Guid.TryParse(text, out var parsed))\n" +
                "        {\n" +
                "            value = default;\n" +
                "            return false;\n" +
                "        }\n",
            "global::System.Int32" =>
                "        if (!global::System.Int32.TryParse(\n" +
                "                text,\n" +
                "                global::System.Globalization.NumberStyles.Integer,\n" +
                "                global::System.Globalization.CultureInfo.InvariantCulture,\n" +
                "                out var parsed))\n" +
                "        {\n" +
                "            value = default;\n" +
                "            return false;\n" +
                "        }\n",
            "global::System.Int64" =>
                "        if (!global::System.Int64.TryParse(\n" +
                "                text,\n" +
                "                global::System.Globalization.NumberStyles.Integer,\n" +
                "                global::System.Globalization.CultureInfo.InvariantCulture,\n" +
                "                out var parsed))\n" +
                "        {\n" +
                "            value = default;\n" +
                "            return false;\n" +
                "        }\n",
            _ =>
                $"        if (!{underlying}.TryParse(text, out var parsed))\n" +
                "        {\n" +
                "            value = default;\n" +
                "            return false;\n" +
                "        }\n"
        };

        return
            $"    public static bool TryParse(string? text, out {name} value)\n" +
            "    {\n" +
            "        if (string.IsNullOrWhiteSpace(text))\n" +
            "        {\n" +
            "            value = default;\n" +
            "            return false;\n" +
            "        }\n" +
            "\n" +
            parseBody +
            "        value = new(parsed);\n" +
            "        return true;\n" +
            "    }\n";
    }

    private static string EmitMustParse(StrongIdModel model)
    {
        var name = model.Name;

        return
            $"    public static {name} MustParse(string text)\n" +
            "    {\n" +
            "        if (string.IsNullOrWhiteSpace(text))\n" +
            "        {\n" +
            "            throw new global::System.ArgumentException(\"Value cannot be null or whitespace.\", nameof(text));\n" +
            "        }\n" +
            "\n" +
            $"        if (!TryParse(text, out var value))\n" +
            "        {\n" +
            $"            throw new global::System.FormatException($\"Unable to parse {name} from '{{text}}'.\");\n" +
            "        }\n" +
            "\n" +
            "        return value;\n" +
            "    }\n";
    }

    private static string AccessibilityToCSharp(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedAndInternal => "private protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        _ => "internal"
    };
}

public class StrongIdModel
{
    public string Namespace { get; set; } = null!;
    public string Name { get; set; } = null!;
    public Accessibility Accessibility { get; set; }
    public string UnderlyingTypeDisplay { get; set; } = null!;
}